name = "LowOrderLegendre"
uuid = "25f81d33-b422-42fe-a8f0-9b88fccc70a7"
authors = ["Haroun Meghaichi"]
version = "0.0.1"

[deps]
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
LegendrePolynomials = "0.4.5"
Match = "2.3.0"
Polynomials = "4.0.12"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
